/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grafica;
import logica.SimulacionCredito;
import dto.Cliente;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
  import javax.swing.JOptionPane; 
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author santi
 */
public class Ventana extends javax.swing.JFrame {
 private DefaultTableModel modelTabla;
 private List<SimulacionCredito> Lista;
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        Datos();
        initComponents();
         Lista = new ArrayList();
        this.CargarSimu(PROPERTIES);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cjNombre = new javax.swing.JTextField();
        cjIdentificacion = new javax.swing.JTextField();
        CjDinero = new javax.swing.JTextField();
        cjMeses = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cjNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjNombreActionPerformed(evt);
            }
        });
        cjNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cjNombreKeyPressed(evt);
            }
        });

        cjIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjIdentificacionActionPerformed(evt);
            }
        });
        cjIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cjIdentificacionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cjIdentificacionKeyTyped(evt);
            }
        });

        CjDinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CjDineroActionPerformed(evt);
            }
        });
        CjDinero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CjDineroKeyTyped(evt);
            }
        });

        cjMeses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjMesesActionPerformed(evt);
            }
        });
        cjMeses.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cjMesesKeyTyped(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Identificacion");

        jLabel3.setText("Dinero que desea solicitar");

        jLabel4.setText("Numero de meses a pagar");

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "COLLUM1", "COLLUM2", "COLLUM3", "COLLUM4", "COLLUM5", "COLLUM6", "COLLUM7"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton2.setText("Pagar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(cjMeses)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cjNombre)
                            .addComponent(cjIdentificacion)
                            .addComponent(CjDinero)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cjNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cjIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CjDinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cjMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    CrearSoli() ;       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cjNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cjNombreActionPerformed

    private void cjIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjIdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cjIdentificacionActionPerformed

    private void CjDineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CjDineroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CjDineroActionPerformed

    private void cjMesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjMesesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cjMesesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
      mDatos();
        jTable2.setModel(new DefaultTableModel());
        String  cedula = JOptionPane.showInputDialog("Digite número de cédula a modificar");
     
        SimulacionCredito persona = null;
         Cliente r = new Cliente();
            float di=r.obtenerDinero() ;
            String d = String.valueOf(di);
            
              float me=r.obtenerMeses() ;
            String m = String.valueOf(me);
            
            
        for (SimulacionCredito person : Lista) {
            if (cedula.equals(r.obtenerIdentificacion())) {
                persona = person;
            } 
        }
        if (persona != null) {
            cjNombre.setVisible(true);
            cjIdentificacion.setVisible(true);
            CjDinero.setText(d);
            cjMeses.setText(m);  
            CjDinero.setVisible(false);
             cjNombre.setEditable(false);
            cjIdentificacion.setEditable(true);
        } else {
            
            JOptionPane.showMessageDialog(this, "La cedula " + cedula + " no existe");
        }  
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cjIdentificacionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cjIdentificacionKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cjIdentificacionKeyPressed

    private void cjIdentificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cjIdentificacionKeyTyped
         char c= evt.getKeyChar();
         if(c<'0'||c>'9') evt.consume();
    }//GEN-LAST:event_cjIdentificacionKeyTyped

    private void CjDineroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CjDineroKeyTyped
        // TODO add your handling code here:
         char c= evt.getKeyChar();
         if(c<'0'||c>'9' || c=='.') evt.consume();
    }//GEN-LAST:event_CjDineroKeyTyped

    private void cjMesesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cjMesesKeyTyped
        // TODO add your handling code here:
        char c= evt.getKeyChar();
         if(c<'0'||c>'9') evt.consume();
    }//GEN-LAST:event_cjMesesKeyTyped

    private void cjNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cjNombreKeyPressed
        char c= evt.getKeyChar();
         //if((c<'a'||c>'z' ) && (c<'A'||c>'Z' )) evt.consume();
    }//GEN-LAST:event_cjNombreKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    public void mDatos() {       
//         cjNombre.setVisible(false);
//      cjIdentificacion.setVisible(false);
//      CjDinero.setVisible(false);
//        cjMeses.setVisible(false);
//       
//      
   }
    private void CrearSoli(){
        
        SimulacionCredito a = new  SimulacionCredito();
        
           String nombre = cjNombre.getText();
        int identificacion = Integer.parseInt(cjIdentificacion.getText());
        float dinero = Float.parseFloat(CjDinero.getText());
        int meses = Integer.parseInt(cjMeses.getText());
         double interes =0;
          double pagoMensual =500000;

          Cliente r = a.crearSoli(nombre, identificacion, dinero, meses,interes);
        //  String interesS = String.valueOf(r.obtenerInteres());
          String coutaM=String.valueOf(pagoMensual);
            if ( nombre.isBlank() || 
                    identificacion<0 
                    ||meses<0||
               
                    dinero <0
                    || dinero<10000
                    ||dinero>100000000 ||
                  nombre.matches("1-9")){
                 JOptionPane.showMessageDialog(this, "No creo la simulacion");
            
            //JOptionPane.showMessageDialog(this, "Creo la simulacion ->"+r);
            }
            else{
            this.CargarSimu(coutaM);
            }
    }
   
    
    
    private void CargarSimu(Object pagoMensual){
  
 
       DefaultTableModel tabla = new DefaultTableModel();
       // tabla.addColumn("Codigo");
        tabla.addColumn("Nombre");
          tabla.addColumn("Valor de couta");
        tabla.addColumn("Dinero");
        tabla.addColumn("Interes");
        tabla.addColumn("Numero de cuotas");
         tabla.addColumn("Numero de identificaicon");
         SimulacionCredito a = new  SimulacionCredito();
               Map<String,Cliente> lista = a.ObtenerLista();
               for (Map.Entry<String, Cliente> dato : lista.entrySet()) {
                   Cliente c = dato.getValue();
                    double   total = c.obtenerDinero() * c.obtenerInteres();
                  int pagoMensua1 = (int) (total / c.obtenerIdentificacion()); 
                  
                Object data[]={
                  //c.getCodigo(),
                    c.obtenerNombre(),
                    c.obtenerIdentificacion(),
                    c.obtenerDinero(),
                    c.obtenerInteres(),
                    pagoMensua1,
                    c.obtenerMeses()
                    
                };
                 tabla.addRow(data);
             }
                       
                 this.jTable2.setModel(tabla);
                 
    
    }
    
             //    try{
           //FileWriter salvar = new FileWriter("simulaciones.txt");
           //for(int i=0;i<this.jTable2.getRowCount();i++){
           //salvar.write(tabla.getValueAt(i,0).toString()+" ");
           // salvar.write(tabla.getValueAt(i,6).toString()+" ");
               //    }
             //    }
           //catch(Exception x){
                   //}
           
           
       
        //,valorInteres,pagoMensual,total
    //  ,double valorInteres,double pagoMensual, double total
        
      private void Datos() {
       mDatos();   
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CjDinero;
    private javax.swing.JTextField cjIdentificacion;
    private javax.swing.JTextField cjMeses;
    private javax.swing.JTextField cjNombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

   
}
